### ISSUE TITLE
How to validate Enums

### ISSUE THREAD

**Issue by codebreach** [lucono/xtypejs#1]
We have a bunch of code that looks like the 'before' in your examples.
However we also need to validate enums, ensuring that the value is one of a list of strings or objects.
I am pretty sure I checked all the docs and didn't find this, any chance of getting some isEnum type functionality that basically does arr1 && indexOf type checks?

**Comment by lucono** [comment]
Are your enums simple strings or implemented as an actual "type"? Do you have some sample code to illustrate? If your enums are implemented as just strings, then they wouldn't appear as a proper type other than the "string" type.

xtypejs supports [Instance Type](http://xtype.js.org/?doc=types&item=instance_types), which would allow you to validate your enum, as long as it's implemented as a proper type (for instance, a WeekDay type representing the days of the week).

If you can provide some sample code of your current implementation, I could try to provide some code examples of an [Instance Type](http://xtype.js.org/?doc=types&item=instance_types) based solution.

**Comment by codebreach** [comment]
We have both instance types and string types.
The instance types are obviously supported as you mentioned. My request was for string types:
````
var STATES = {
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
};

var objectToBeValidated = {
  state: STATES.ACCEPTED
};
````
Now I want to do something like:
````
xtypejs.isEnum(objectToBeValidated.state, STATES)
````
I am not sure how this would work with `.type` since it really is a string as you pointed out.

**Comment by bjmiller** [comment]
Can registerTypes handle this?  It looks close, but you'd probably need for it to accept a custom function that can test for whether an arbitrary thing passed in meets the criteria for the new type.

Also, you would probably need to allocate a higher-number space for custom-type ID numbers to live in.

**Comment by lucono** [comment]
A registerTypes approach would have to be implemented in a way that keeps the new type completely compatible with any other built-in or previously registered types, which might be possible. Definitely worth exploring ..will look into it.

**Comment by lucono** [comment]
After exploring the registerTypes approach to this, I'm going to go ahead and implement it, after which you can give it a try for your use case and provide feedback based on that.

**Comment by codebreach** [comment]
Woohoo. Thanks for the quick turnaround. Looking forward to using this.

**Comment by lucono** [comment]
Created #2 for the implementation of the custom validation feature.

**Comment by lucono** [comment]
xtypejs supports [Instance Types](http://xtype.js.org/types/instance_types), which are able to validate Enums implemented as actual enum types. More in this [comment](https://github.com/lucono/xtypejs/issues/1#issuecomment-117724284).

For arbitrary custom validation, see issue #2.
